export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const PUT_DATA_SUCCESS = 'PUT_DATA_SUCCESS';
export const GET_POSTALCODE_VALIDATION_DATA_SUCCESS = 'GET_POSTALCODE_VALIDATION_DATA_SUCCESS';
export const GET_JIRA_DATA_SUCCESS = 'GET_JIRA_DATA_SUCCESS';